version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: banco
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql: